GET http://localhost:3306/

###

GET http://localhost:3306/all-tasks

###

POST http://localhost:3306/create-task
Content-Type: application/json

{
  "titulo": "Piratas do Caribe: a vingaça de salazar",
  "genero": "ação, aventura",
  "classificacao": 12,
  "duracao": 130
}


###
DELETE http://Localhost:3306/delete-task/1

###

PUT http://localhost:3306/update-task/15
Content-Type: application/json

{
    "titulo": "Piratas do Caribe: a vingança de salazar",
    "genero": "ação, aventura",
    "classificacao": 12,
    "duracao": 130
}